name: Build Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      # Cancel any in-progress workflows when this action starts, which mostly
      # only matters if a webhook trigger is later added.
      cancel-in-progress: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Cache Gatsby
        uses: actions/cache@v3
        id: gatsby
        with:
          path: |
            .cache
            public
          # We have to not include the string "gatsby" in the cache name.
          # Otherwise, the cache will be busted on every build.
          key: ${{ runner.os }}-build-cache

      - name: Install Packages
        run: npm ci --ignore-scripts --prefer-offline --no-audit

      - name: Build Gatsby
        run: npm run build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
