name: Build Gatsby Site

on:
  push:
    branches:
      - main

# Cancel any in-progress workflows when this action starts, which mostly only
# matters if a webhook trigger is later added.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Cache Gatsby
        uses: actions/cache@v3
        id: gatsby
        with:
          path: |
            .cache
            public
          # We have to not include the string "gatsby" in the cache name.
          # Otherwise, the cache will be busted on every build.
          key: ${{ runner.os }}-build-cache

      - name: Install Packages
        run: npm ci --ignore-scripts --prefer-offline --no-audit

      - name: Build Gatsby
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: npm run build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
